### ISSUE TITLE
사용허가 요청

### ISSUE THREAD

**Issue by kgt0205** [white-201/discord-bot-autoselfcheck#1]
해당 레포지토리 오픈소스를 사용 하고 싶어, 사용 허가를 요청 드립니다.

**Comment by junah201** [comment]
@geuntae021 사용 용도에 대해서 설명해주실 수 있으신가요?

**Comment by kgt0205** [comment]
> @geuntae021 사용 용도에 대해서 설명해주실 수 있으신가요?

디스코드 봇 개발 참고 입니다

**Comment by junah201** [comment]
> > @geuntae021 사용 용도에 대해서 설명해주실 수 있으신가요?
> 
> 디스코드 봇 개발 참고 입니다

출처만 명확하게 밝혀주세요.
